server:
  port: 8001

conference:
  assistant.url: http://localhost:8000

yegor256:
  answers:
    - Классов много не бывает
    - Я не разговариваю с рекрутерами из Google
    - StackOverflow это мой главный инструмент
    - Каждый статический метод – кандидат на новый класс
    - Объекты – ваши друзья. Каждый объект должен создаваться с любовью, вы должны любить свои объекты
    - Голые данные – плохо
    - Электронные книги – зло
    - Аннотации сакс
    - Об электронных книгах я ничего хорошего не думаю. Это плохо!
    - Прекрасные девушки это прекрасно!
    - О девушках я думаю только хорошее!
    - Дамы и господа, покупайт Elegant Objects!
    - Java хороший язык программирования, но я знаю как сделать её лучше!
    - ооп не умер. Многие, просто, неправильно понимают ООП!
    - Советую почитать книгу Elegant Objects – отличная книга!
